common/models/Lection.php
<?php

namespace common\models;

use Yii;
use common\components\MetaBehavior;
use common\components\StrBehavior;

/**
 * This is the model class for table "lection".
 *
 * @property integer $id
 * @property integer $meta_id
 * @property string $name
 * @property string $url
 * @property string $video_id
 * @property string $short_description
 * @property string $full_description
 *
 * @property Meta $meta
 */
class Lection extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lection';
    }

    public function behaviors()
    {
        return [
            MetaBehavior::className(),
            StrBehavior::className()
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['meta_id', 'name', 'url', 'video_id', 'short_description', 'full_description'], 'required'],
            [['meta_id'], 'integer'],
            [['short_description', 'full_description'], 'string'],
            [['name', 'url', 'video_id'], 'string', 'max' => 255],
            [['meta_id'], 'exist', 'skipOnError' => true, 'targetClass' => Meta::className(), 'targetAttribute' => ['meta_id' => 'id']],
            ['url', 'unique', 'targetAttribute' => ['url'], 'message' => 'Url должна быть уникальна.'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'meta_id' => 'Meta ID',
            'name' => 'Name',
            'url' => 'Url',
            'video_id' => 'Video ID',
            'short_description' => 'Short Description',
            'full_description' => 'Full Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeta()
    {
        return $this->hasOne(Meta::className(), ['id' => 'meta_id']);
    }

    public function getVideoThumb()
    {
//        return null;
        return "https://img.youtube.com/vi/$this->video_id/0.jpg";
    }
}

common/controllers/LectionController.php
<?php

namespace common\controllers;

use Yii;
use common\models\Lection;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LectionController implements the CRUD actions for Lection model.
 */
class LectionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Lection models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Lection::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Lection model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => Lection::findOne($id),
        ]);
    }

    /**
     * Creates a new Lection model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Lection();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Lection model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = Lection::findOne($id)->meta();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Lection model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        Lection::findOne($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Lection model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Lection the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
//    protected function findModel($id)
//    {
//        if (($model = Lection::findOne($id)) !== null) {
//            return $model;
//        } else {
//            throw new NotFoundHttpException('The requested page does not exist.');
//        }
//    }
}

frontend/controllers/LectionController.php
<?php
namespace frontend\controllers;

use common\models\Author;
use Yii;
use common\models\Lection;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\helpers\VarDumper;

/**
 * Site controller
 */
class LectionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Lection::find(),
            'pagination' => [
                'pageSize' => 3
            ]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionView($url)
    {
        $model = Lection::findOne(['url' => $url]);

        $user = Yii::$app->user->identity;

        $dataProvider = new ActiveDataProvider([
            'query' => Lection::find()
        ]);

        return $this->render($user && $user->getIsAccess($model->id) ? 'view' : 'preview', [
            'model' => $model,
            'dataProvider' => $dataProvider
        ]);
    }
}

frontend/views/lection/cart_item.php
<?
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<br>
<section>
    <div class="container">
        <div class="row">
            <div class="grid_3">
                <img src='<?= $model->videoThumb ?>' alt='<?= $model->name ?>' class="lection-cart">
            </div>
            <div class="grid_9">
                <p class="h4"><?= $model->name ?></p>
                <? ActiveForm::begin(['action' => ['cart/remove']])?>
                <?= Html::hiddenInput('id', $model->id) ?>
                <?= Html::submitButton('Удалить', ['class' => 'btn btn-danger']) ?>
                <? ActiveForm::end()?>
            </div>
        </div>
        <br>
    </div>
</section>

frontend/views/lection/index.php
<?
use yii\widgets\ListView;
?>
<?
$this->title = 'Лекции';
//$this->params['breadcrumbs'][] = $this->title;
?>

<section class="well ins3 mobile-center">
    <div class="container">
        <h3>Лекции:</h3>

        <?=
        ListView::widget([
            'dataProvider' => $dataProvider,
            'layout' => '{items}',
            'options' => ['class' => 'row'],
            'itemOptions' => ['class' => 'grid_4'],
            'itemView' => 'index_item'
        ])
        ?>

    </div>
</section>
<section data-url="images/parallax7.jpg" data-mobile="true" class="well2 center parallax">
    <h2>Некий<em>банер<br/>о чем-то!</em></h2>
</section>

frontend/views/lection/index_item.php
<?
use yii\helpers\Url;
?>

<img src='<?= $model->videoThumb ?>' alt='<?= $model->name ?>'>
<h5 class="fixed-height-90">
    <a href="<?= Url::toRoute(['lection/view', 'url' => $model->url]) ?>"><?= $model->name ?>.</a>
</h5>
<p class="short_description"><?= $model->getCut('short_description', 200) ?></p>
<a href="<?= Url::toRoute(['lection/view', 'url' => $model->url]) ?>" class="btn2">Читать</a>

frontend/views/lection/main.php
<?
use yii\helpers\Url;
use yii\helpers\Html;
?>
<p class='h2'><?= $model->name ?></p>

<p class='text-info'><?= $model->getCut('short_description', 100) ?></p>
<p class='lead'><?= $model->getCut('full_description', 300) ?></p>
<?= Html::img($model->videoThumb, ['class' => 'main-lection-thumb']) ?>
<p>
    <a class="btn btn-default" href='<?= Url::toRoute(['lection/view', 'url' => $model->url]) ?>'>
        Далее &raquo;
    </a>
</p>

frontend/views/lection/preview.php
<?
use yii\widgets\ListView;
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>
<?
$this->title = $model->meta->title;
$this->params['breadcrumbs'][] = ['label' => 'Лекции', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section>
    <div class="container">
        <div class="row">
            <div class="grid_8">
                <div class="row">
                    <div class="col-md-12">
                        <h1><?= $model->name ?></h1>
                        <p class="text-muted"><?= date('Y-m-d h:m:i') ?></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <img src='<?= $model->videoThumb ?>' alt='<?= $model->name ?>' class='lection-preveiw'>
                        <div><?= $model->full_description ?></div>
                    </div>
                </div>
            </div>
            <div class="grid_1"></div>
            <div class="grid_3">
                <?=
                ListView::widget([
                    'dataProvider' => $dataProvider,
                    'layout' => '{items}',
                    'options' => ['class' => 'row'],
                    'itemOptions' => ['class' => 'col-md-10 col-md-offset-1 lection-side'],
                    'itemView' => '/lection/side'
                ])
                ?>
            </div>
            <div class="grid_8">
                <p class="h4">Получить доступ к видео можно как угодно</p>
                <p class="h5">К примеру, внести оплату на одну из многочисленных платежных систем <span class="text-muted">(кроме заблокированных)</span></p>
                <img src="https://i.io.ua/img_su/large/0233/37/02333770_n1.jpg" alt="" width="100%">
            </div>
            <div class="grid_3">
                <? $form = ActiveForm::begin(['action' => ['cart/add']]) ?>
                <?= Html::hiddenInput('id', $model->id) ?>
                <?= Html::submitButton('Получить доступ', ['class' => 'btn btn-primary']) ?>
                <? ActiveForm::end() ?>
            </div>
        </div>
    </div>
</section>

frontend/views/lection/side.php
<?
use yii\helpers\Url;
use yii\helpers\Html;
?>
<br>
<a href='<?= Url::toRoute(['lection/view', 'url' => $model->url]) ?>'>
    <strong><?= $model->name ?></strong>
    <?= Html::img($model->videoThumb, ['class' => 'side-lection-thumb']) ?>
</a>

frontend/views/lection/view.php
<??>