common/models/Lection.php
<?php

namespace common\models;

use Yii;
use common\components\MetaBehavior;
use common\components\StrBehavior;

/**
 * This is the model class for table "lection".
 *
 * @property integer $id
 * @property integer $meta_id
 * @property string $name
 * @property string $url
 * @property string $video_id
 * @property string $short_description
 * @property string $full_description
 *
 * @property Meta $meta
 */
class Lection extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'lection';
    }

    public function behaviors()
    {
        return [
            MetaBehavior::className(),
            StrBehavior::className()
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['meta_id', 'name', 'url', 'video_id', 'short_description', 'full_description'], 'required'],
            [['meta_id'], 'integer'],
            [['short_description', 'full_description'], 'string'],
            [['name', 'url', 'video_id'], 'string', 'max' => 255],
            [['meta_id'], 'exist', 'skipOnError' => true, 'targetClass' => Meta::className(), 'targetAttribute' => ['meta_id' => 'id']],
            ['url', 'unique', 'targetAttribute' => ['url'], 'message' => 'Url должна быть уникальна.'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'meta_id' => 'Meta ID',
            'name' => 'Name',
            'url' => 'Url',
            'video_id' => 'Video ID',
            'short_description' => 'Short Description',
            'full_description' => 'Full Description',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeta()
    {
        return $this->hasOne(Meta::className(), ['id' => 'meta_id']);
    }

    public function getVideoThumb()
    {
//        return null;
        return "https://img.youtube.com/vi/$this->video_id/0.jpg";
    }
}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Author;
use common\models\Blog;
use common\models\Subscribe;
use Yii;
use yii\base\InvalidParamException;
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use common\models\LoginForm;
use common\models\Lection;
use common\models\Mailer;

use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
//                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $lectionDataProvider = new ActiveDataProvider([
            'query' => Lection::find()->where(['id' => [1,2,3]])
        ]);

        $authorDataProvider = new ActiveDataProvider([
            'query' => Author::find()
        ]);

        $articleDataProvider = new ActiveDataProvider([
            'query' => Blog::byOwner()->getArticles()
        ]);

        $lectionOnMain = Blog::byOwner()->getArticles()->where(['id' => 3])->one();
        $videoOnMain = Lection::find()->where(['id' => 1])->one();

        return $this->render('index',[
            'lectionDataProvider'   => $lectionDataProvider,
            'authorDataProvider'    => $authorDataProvider,
            'articleDataProvider'   => $articleDataProvider,
            'lectionOnMain'         => $lectionOnMain,
            'videoOnMain'           => $videoOnMain
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack(Url::previous());
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('/contact/view', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionCabinet()
    {
        if (Yii::$app->user->isGuest) {
            Url::remember(Yii::$app->request->url);
            return $this->redirect(Url::toRoute(['site/login']));
        }

        $user = Yii::$app->user->identity;
        $lectionDataProvider = new ActiveDataProvider([
            'query' => $user->getAccess()
        ]);

        return $this->render('/user/cabinet',[
            'lectionDataProvider' => $lectionDataProvider
        ]);
    }

    public function actionSubscribe()
    {
        $post = Yii::$app->request->post();
        $model = Yii::$app->mailer;

        if($post && $model->load($post))
        {
            $resp = $model->compose(
                'Обновления medfiles.me',       //subject
                ['template' => 'subscribe']     //message options [template,...custom variables]
            )
                ->send();
            $subscribe = new Subscribe();

            $subscribe->attributes = [
                'username'  => $model->getUsername(),
                'useremail' => $model->getUseremail(),
                'sended'    => $resp->statusCode()
            ];

            $subscribe->save();

            return $this->redirect(Url::toRoute(['site/index']));
        }

        return $this->render('subscribe',[]);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\widgets\ListView;
use yii\helpers\Url;

$this->title = 'Главная';

?>
<?/*<section class="camera_container">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <?= $this->render('subscribe_form') ?>
            </div>
        </div>
    </div>
</section>*/?>
<section data-mobile="true" class="camera_container left" id="subcribe_home">
    <div class="container">
        <div class="row">
            <h2 class="site-index">
                <em>Экспертная медицинская <br> информация для каждого</em>
            </h2>
            <article class="grid_3">
                <a href="<?= Url::toRoute(['site/subscribe']) ?>" class="btn site-index">1</a>
            </article>
            <div class="grid_3">
                <a href="" class="btn site-index">2</a>
            </div>
        </div>
    </div>
    <?/*<div class="container">
        <div class="row">
            <div class="grid_4" style="visibility: hidden">
                <div class="promo-subscribe-bg">
                    <div class="promo-subscribe-text">
                        <div class="custom_index_site" style="text-align: center;">Здравствуйте!</div>
                        <div class="custom_index_site"><em>Оформляя подписку - Вы получаете доступ ко всем
                                курсам, а также к их материалам и тестам.</em>
                    </div>
                    </div>
                    <div class="promo-post-card">
                        <?= $this->render('subscribe_form') ?>
                    </div>
                </div>
            </div>
        </div>
    </div>*/?>
</section>
<section class="well1">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h5 class="title_section_home">Статьи</h5>
            </div>
        </div>
        <?=
        ListView::widget([
            'dataProvider' => $articleDataProvider,
            'layout' => '{items}',
            'options' => [
                'class' => 'row'
            ],
            'itemOptions' => [
                'class' => 'grid_4',
                'tag'   => 'article'
            ],
            'itemView' => '/article/main/main'
        ])
        ?>
    </div>
</section>
<section class="well bg-color">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h5 class="title_section_home">Блог</h5>
            </div>
        </div>
        <div class="row">
            <div class="grid_5"><img src="images/page-1_img01.jpg" alt=""></div>
            <div class="grid_7">
                <h3><?= $lectionOnMain->name ?></h3>
                <div class="short_description">
                    <?= $lectionOnMain->getCut('short_description', 300) ?>
                </div>
                <a href="<?= Url::toRoute(['article/view', 'url' => $lectionOnMain->url]) ?>" class="btn">Читать</a>
            </div>
        </div>
    </div>
</section>
<section class="well">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h5 class="title_section_home">Лекции</h5>
            </div>
        </div>
        <div class="row">
            <div class="grid_6">
                <h3><?= $videoOnMain->name ?></h3>
                <div class="short_description">
                    <?= $videoOnMain->getCut('short_description', 300) ?>
                </div>
                <a href="<?= Url::toRoute(['lection/index']) ?>" class="btn btn-lg">Лекции</a>
            </div>
            <div class="grid_6">
                <a href="<?= Url::toRoute(['lection/view', 'url' => $videoOnMain->url]) ?>" class="thumb thumb_video mg-add fancybox.iframe">
                    <img src="<?= $videoOnMain->videoThumb ?>" alt="<?= $videoOnMain->name ?>">
                    <span class="thumb_overlay"></span>
                </a>
            </div>
        </div>
    </div>
</section>
<?/*
<section data-url="images/parallax1.jpg" data-mobile="true" class="well2 center parallax">
    <h2>Предложение<em>Высококачественное медицинское<br>обслуживание и лечение</em></h2>
</section>
*/?>
<section class="well ins1 bg-color">
    <div class="container">
        <div class="row">
            <div class="grid_12">
                <h5 class="title_section_home">Что дает хорошая медицинская информация:</h5>
            </div>
        </div>
        <ul class="product-list row">
            <li class="grid_6">
                <div class="box">
                    <div class="box_aside">
                        <div class="fa-medkit bg-secondary2"></div>
                    </div>
                    <div class="box_cnt__no-flow">
<!--                        <h4>Aculis lacinia</h4>-->
                        <p class="text-medium">
                            Позволяет эффективно бороться с болезнью: Вы знаете причины болезни и можете ее избежать; Вы знаете первые симптомы и обращаетесь за помощью вовремя; Вы знаете критерии качества лечения и способны его контролировать.
                        </p>
                    </div>
                </div>
                <div class="box">
                    <div class="box_aside">
                        <div class="fa-heart bg-primary"></div>
                    </div>
                    <div class="box_cnt__no-flow">
<!--                        <h4>Estproin dictum</h4>-->
                        <p class="text-medium">Убирает страх и тревогу: вместо страха неопределенности и неизвестности болезни Вы точно знаете угрозы, которые несет болезнь и как с ними можно бороться. Вы контролируете проблему и спокойны.</p>
                    </div>
                </div>
            </li>
            <li class="grid_6">
                <div class="box">
                    <div class="box_aside">
                        <div class="fa-group bg-secondary"></div>
                    </div>
                    <div class="box_cnt__no-flow">
<!--                        <h4>Proin dictum</h4>-->
                        <p class="text-medium">
                            Помогает оптимизировать расходы: Вы знаете, как избежать болезни; Вы обращаетесь за помощью при появлении первых симптомов; Вы знаете о возможностях лечения и его эффективности, поэтому Вам легче выбрать оптимальный вариант лечения.
                        </p>
                    </div>
                </div>
                <div class="box">
                    <div class="box_aside">
                        <div class="fa-ambulance bg-secondary3"></div>
                    </div>
                    <div class="box_cnt__no-flow">
<!--                        <h4>Lementum velit</h4>-->
                        <p class="text-medium">
                            Облегчает помощь близким в случае их болезни: все это относится не только к Вам, но и к тем, кто Вам дорог, кому Вы хотите помочь.
                        </p>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</section>
<!--<section class="well bg-color">-->
<!--    <div class="container">-->
<!--        <h3>Gallery</h3>-->
<!--        <div class="row">-->
<!--            <div class="grid_4"><a href="images/page-1_img03_original.jpg" data-fancybox-group="1" class="thumb"><img src="images/page-1_img03.jpg" alt=""><span class="thumb_overlay"></span></a></div>-->
<!--            <div class="grid_4"><a href="images/page-1_img04_original.jpg" data-fancybox-group="1" class="thumb"><img src="images/page-1_img04.jpg" alt=""><span class="thumb_overlay"></span></a></div>-->
<!--            <div class="grid_4"><a href="images/page-1_img05_original.jpg" data-fancybox-group="1" class="thumb"><img src="images/page-1_img05.jpg" alt=""><span class="thumb_overlay"></span></a></div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--            <div class="grid_4"><a href="images/page-1_img06_original.jpg" data-fancybox-group="1" class="thumb"><img src="images/page-1_img06.jpg" alt=""><span class="thumb_overlay"></span></a></div>-->
<!--            <div class="grid_4"><a href="images/page-1_img07_original.jpg" data-fancybox-group="1" class="thumb"><img src="images/page-1_img07.jpg" alt=""><span class="thumb_overlay"></span></a></div>-->
<!--            <div class="grid_4"><a href="images/page-1_img08_original.jpg" data-fancybox-group="1" class="thumb"><img src="images/page-1_img08.jpg" alt=""><span class="thumb_overlay"></span></a></div>-->
<!--        </div>-->
<!--        <div class="btn_wr center"><a href="#" class="btn btn-lg">View all</a></div>-->
<!--    </div>-->
<!--</section>-->
<!--<section data-url="images/parallax2.jpg" data-mobile="true" class="well2 center parallax">-->
<!--    <h2>Current<em>diagnosis and treatment<br/>methods</em></h2>-->
<!--</section>-->
<?/*<section class="well3">
    <div class="container">
        <ul class="pricing-table row">
            <li class="grid_4">
                <h5>Plan 1</h5>
                <div class="price">45</div>
                <ul>
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>consuer adipiscing elit. Praesent </li>
                    <li>vestibulum molestie lacus</li>
                    <li>Aenean nonummy hendrerit</li>
                </ul><a href="#" class="btn">Sign Up</a>
            </li>
            <li class="grid_4 active">
                <h5>Plan 2</h5>
                <div class="price">69</div>
                <ul>
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>consuer adipiscing elit. Praesent </li>
                    <li>vestibulum molestie lacus</li>
                    <li>Aenean nonummy hendrerit</li>
                </ul><a href="#" class="btn">Sign Up</a>
            </li>
            <li class="grid_4">
                <h5>Plan 3</h5>
                <div class="price">55</div>
                <ul>
                    <li>Lorem ipsum dolor sit amet</li>
                    <li>consuer adipiscing elit. Praesent </li>
                    <li>vestibulum molestie lacus</li>
                    <li>Aenean nonummy hendrerit</li>
                </ul><a href="#" class="btn">Sign Up</a>
            </li>
        </ul>
    </div>
</section>*/?>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<section>
    <div class="container">
        <div class="row">
            <div class="site-login">
                <h4 class="tittle"><?= Html::encode($this->title) ?></h4>
                <p style="margin-bottom: 10px">Пожалуйста заполните поля ниже:</p>

                <?php
                $form = ActiveForm::begin([
                    'id' => 'login-form',
                ]);
                ?>

                <label for="username">
                    <?= $form->field($model, 'username')->textInput([
                        'autofocus'   => true,
                        'placeholder' => 'Логин',
                        'class'       => 'input-text'
                    ])->label(false)
                    ?>
                </label>

                <label for="password">
                    <?= $form->field($model, 'password')->passwordInput([
                        'placeholder' => 'Пароль',
                        'class'       => 'input-text'
                    ])->label(false) ?>
                </label>

                <div style="position: relative">
                <div style="font-size: 90%; line-height: 17px; display: inline-block;">
                    <?= $form->field($model, 'rememberMe')->checkbox()->label('запомнить меня') ?>
                </div>
                <div class="forget_pass" style="">
                    <?= Html::a('Забыли пароль?', ['site/request-password-reset']) ?>
                </div>
                </div>

                <div class="btn-wrapper">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>

                <div style="text-align: center; font-style: italic; font-size: 80%;">
                    Еще не зарегистрированы? <a href="/site/signup" style="border-bottom: 1px dotted;">Перейти к регистрации</a>
                </div>
            </div>
        </div>
    </div>
</section>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <div class="container">
        <div class="row">
            <div class="site-login">
                <h4 class="tittle"><?= Html::encode($this->title) ?></h4>
                <p style="margin-bottom: 10px">Пожалуйста, введите Ваш e-mail.</p>

                <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <label for="email">
                    <?= $form->field($model, 'email')->textInput([
                        'autofocus' => true,
                        'class'     => 'input-text'
                    ])->label(false) ?>
                </label>

                <div class="btn-wrapper">
                    <?= Html::submitButton('Сбросить пароль', ['class' => 'btn btn-primary']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">

    <div class="container">
        <div class="row">
            <div class="site-login">
                <h4 class="tittle"><?= Html::encode($this->title) ?></h4>
                <p style="margin-bottom: 10px">Please choose your new password:</p>

                <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <label for="password">
                    <?= $form->field($model, 'password')->passwordInput([
                        'autofocus' => true,
                        'class'     => 'input-text'
                    ])->label(false) ?>
                </label>

                <div class="btn-wrapper">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="container">
        <div class="row">
            <div class="site-login">
                <h4 class="tittle"><?= Html::encode($this->title) ?></h4>
                <p style="margin-bottom: 10px">Please fill out the following fields to signup:</p>


                <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'class' => 'input-text'])->label('Логин') ?>

                <?= $form->field($model, 'email')->textInput(['class' => 'input-text'])->label('E-mail') ?>

                <?= $form->field($model, 'password')->passwordInput(['class' => 'input-text'])->label('Пароль') ?>

                <div class="btn-wrapper">
                    <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>

                <div style="text-align: center; font-style: italic; font-size: 80%;">
                    Уже зарегистрированы? <a href="/site/cabinet" style="border-bottom: 1px dotted;">Войти в кабинет</a>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/subscribe_form.php
<?

use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;

?>

<!--<h4>Подпишись на рассылку</h4>-->
<? ActiveForm::begin([
    'action'  => Url::toRoute(['site/subscribe']),
    'id'      => 'post_card',
    'options' => [
        'class' => 'mailform rd-mailform',
    ]
]); ?>

<label for="username">
    <?=
    Html::textInput(
        'username',
        false,
        ['placeholder' => 'Имя',
         'autocomplete' => 'off']
    )
    ?>
</label>

<label for="userphone">
    <?=
    Html::textInput(
        'username',
        false,
        ['placeholder' => 'Телефон',
            'autocomplete' => 'off']
    )
    ?>
</label>

<label for="useremail">
    <?=
    Html::textInput(
        'useremail',
        false,
        ['placeholder' => 'Email']
    )
    ?>
</label>

<div style="text-align: center; margin-top: 20px;">
    <?=
    Html::textInput(null, 'Оформить', ['type' => 'submit', 'class' => 'btn mfProgress'])
    ?>
</div>

<? ActiveForm::end(); ?>